# Gemfile
source 'https://rubygems.org'

ruby '2.1.1'

gem 'sinatra'
gem 'haml'
gem 'i18n'

gem 'sinatra-asset-pipeline', require: 'sinatra/asset_pipeline'
gem 'sinatra-i18n', require: 'sinatra/i18n'

gem 'shotgun'

gem 'cactu'

gem 'sinatra-partial'
